// <auto-generated />
using D2CFL.Migrations.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace D2CFL.Migrations.Migrations.League
{
    [DbContext(typeof(LeagueContext))]
    partial class LeagueContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("D2CFL.Data.League.Contract.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("PositionEntityId");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("TeamEntityId");

                    b.HasKey("Id");

                    b.HasIndex("PositionEntityId");

                    b.HasIndex("TeamEntityId");

                    b.ToTable("Players","league");
                });

            modelBuilder.Entity("D2CFL.Data.League.Contract.PositionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AssistCoefficient");

                    b.Property<double>("DeathCoefficient");

                    b.Property<double>("KillCoefficient");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Positions","league");
                });

            modelBuilder.Entity("D2CFL.Data.League.Contract.TeamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Teams","league");
                });

            modelBuilder.Entity("D2CFL.Data.League.Contract.PlayerEntity", b =>
                {
                    b.HasOne("D2CFL.Data.League.Contract.PositionEntity", "Position")
                        .WithMany("Players")
                        .HasForeignKey("PositionEntityId");

                    b.HasOne("D2CFL.Data.League.Contract.TeamEntity", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamEntityId");
                });
#pragma warning restore 612, 618
        }
    }
}
